# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)



player_list =[
              "Jonathan Agnew",
              "Trevor Bailey",
              "Jack Bannister",
              "Sir Alec Bedser",
              "Scyld Berry",
              "Dickie Bird",
              "Brian Close",
              "Lord Cowdrey",
              "Ted Dexter",
              "Matthew Engel",
              "Alf Gover",
              "Tom Graveney",
              "Frank Keating",
              "Tony Lewis",
              "George Mann",
              "Vic Marks",
              "Christopher Martin-Jenkins",
              "Derek Pringle",
              "Nette Rheinberg",
              "Mike Selvey",
              "EW Swanton",
              "Bob Taylor",
              "Freddie Trueman",
              "Crawford White",
              "John Woodcock",
              "Ian Wooldridge",
              "Peter Wynne-Thomas",
              "Greg Baum",
              "Percy Beames",
              "Richie Benaud",
              "Bill Brown",
              "Richard Cashman",
              "Ian Chappell",
              "Mike Coward",
              "Alan Davidson",
              "Gideon Haigh",
              "Murray Hedgcock",
              "John Inverarity",
              "Bill Lawry",
              "Peter McFarline",
              "Jim Maxwell",
              "Arthur Morris",
              "Bobby Simpson",
              "Cec Starr",
              "Steve Waugh",
              "Ali Bacher",
              "Eddie Barlow",
              "Colin Bryden",
              "Russell Endean",
              "Trevor Goddard",
              "Norman Gordon",
              "Michael Owen-Smith",
              "Peter Pollock",
              "Krish Reddy",
              "Peter van der Merwe",
              "John Waite",
              "Gerry Alex er",
              "Tom Becca",
              "Sir Carlisle Burton",
              "Tony Cozier",
              "Esmond Kentish",
              "Clive Lloyd",
              "Reds Periera",
              "Allan Rae",
              "Donna Symmonds",
              "Sir Clyde Walcott",
              "Sir Everton Weekes ",
              "Mihir Bose",
              "Dilip Doshi",
              "Sunil Gavaskar",
              "Ayaz Memon",
              "Ramesh Mohan",
              "Nirum Prabhu",
              "Raj Singh",
              "Kris Srikkanth",
              "Polly Umrigar",
              "Srinivasaraghavan Venkataraghavan",
              "Dick Brittenden",
              "Don Cameron",
              "Walter Hadlee",
              "Don Neeley",
              "John Reid",
              "Bert Sutcliffe",
              "Lindsay Weir",
              "John Wright",
              "Arif Abbasi",
              "Fereshteh Gati",
              "Hanif Mohammad",
              "Intikhab Alam",
              "Javed Burki",
              "Mushtaq Mohammad",
              "Omar Kureishi",
              "Qamar Ahmed",
              "Stanley Jayasingha",
              "Ranjan Madugalle",
              "Gerry Vaidyasekera ",
              "Dave Houghton "]


player_list.each do |name|
  Player.create( name: name, score: rand * 100 )
end
